// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package cluster

import (
	"context"
	"errors"
	"fmt"
	"math"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/kafka"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/kafka/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/kafka-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.Cluster{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadOneInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newDescribeRequestPayload(r)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.DescribeClusterOutput
	resp, err = rm.sdkapi.DescribeCluster(ctx, input)
	rm.metrics.RecordAPICall("READ_ONE", "DescribeCluster", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "NotFoundException" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if resp.ClusterInfo.BrokerNodeGroupInfo != nil {
		f1 := &svcapitypes.BrokerNodeGroupInfo{}
		if resp.ClusterInfo.BrokerNodeGroupInfo.BrokerAZDistribution != "" {
			f1.BrokerAZDistribution = aws.String(string(resp.ClusterInfo.BrokerNodeGroupInfo.BrokerAZDistribution))
		}
		if resp.ClusterInfo.BrokerNodeGroupInfo.ClientSubnets != nil {
			f1.ClientSubnets = aws.StringSlice(resp.ClusterInfo.BrokerNodeGroupInfo.ClientSubnets)
		}
		if resp.ClusterInfo.BrokerNodeGroupInfo.ConnectivityInfo != nil {
			f1f2 := &svcapitypes.ConnectivityInfo{}
			if resp.ClusterInfo.BrokerNodeGroupInfo.ConnectivityInfo.PublicAccess != nil {
				f1f2f0 := &svcapitypes.PublicAccess{}
				if resp.ClusterInfo.BrokerNodeGroupInfo.ConnectivityInfo.PublicAccess.Type != nil {
					f1f2f0.Type = resp.ClusterInfo.BrokerNodeGroupInfo.ConnectivityInfo.PublicAccess.Type
				}
				f1f2.PublicAccess = f1f2f0
			}
			f1.ConnectivityInfo = f1f2
		}
		if resp.ClusterInfo.BrokerNodeGroupInfo.InstanceType != nil {
			f1.InstanceType = resp.ClusterInfo.BrokerNodeGroupInfo.InstanceType
		}
		if resp.ClusterInfo.BrokerNodeGroupInfo.SecurityGroups != nil {
			f1.SecurityGroups = aws.StringSlice(resp.ClusterInfo.BrokerNodeGroupInfo.SecurityGroups)
		}
		if resp.ClusterInfo.BrokerNodeGroupInfo.StorageInfo != nil {
			f1f5 := &svcapitypes.StorageInfo{}
			if resp.ClusterInfo.BrokerNodeGroupInfo.StorageInfo.EbsStorageInfo != nil {
				f1f5f0 := &svcapitypes.EBSStorageInfo{}
				if resp.ClusterInfo.BrokerNodeGroupInfo.StorageInfo.EbsStorageInfo.ProvisionedThroughput != nil {
					f1f5f0f0 := &svcapitypes.ProvisionedThroughput{}
					if resp.ClusterInfo.BrokerNodeGroupInfo.StorageInfo.EbsStorageInfo.ProvisionedThroughput.Enabled != nil {
						f1f5f0f0.Enabled = resp.ClusterInfo.BrokerNodeGroupInfo.StorageInfo.EbsStorageInfo.ProvisionedThroughput.Enabled
					}
					if resp.ClusterInfo.BrokerNodeGroupInfo.StorageInfo.EbsStorageInfo.ProvisionedThroughput.VolumeThroughput != nil {
						volumeThroughputCopy := int64(*resp.ClusterInfo.BrokerNodeGroupInfo.StorageInfo.EbsStorageInfo.ProvisionedThroughput.VolumeThroughput)
						f1f5f0f0.VolumeThroughput = &volumeThroughputCopy
					}
					f1f5f0.ProvisionedThroughput = f1f5f0f0
				}
				if resp.ClusterInfo.BrokerNodeGroupInfo.StorageInfo.EbsStorageInfo.VolumeSize != nil {
					volumeSizeCopy := int64(*resp.ClusterInfo.BrokerNodeGroupInfo.StorageInfo.EbsStorageInfo.VolumeSize)
					f1f5f0.VolumeSize = &volumeSizeCopy
				}
				f1f5.EBSStorageInfo = f1f5f0
			}
			f1.StorageInfo = f1f5
		}
		ko.Spec.BrokerNodeGroupInfo = f1
	} else {
		ko.Spec.BrokerNodeGroupInfo = nil
	}
	if resp.ClusterInfo.ClientAuthentication != nil {
		f2 := &svcapitypes.ClientAuthentication{}
		if resp.ClusterInfo.ClientAuthentication.Sasl != nil {
			f2f0 := &svcapitypes.SASL{}
			if resp.ClusterInfo.ClientAuthentication.Sasl.Iam != nil {
				f2f0f0 := &svcapitypes.IAM{}
				if resp.ClusterInfo.ClientAuthentication.Sasl.Iam.Enabled != nil {
					f2f0f0.Enabled = resp.ClusterInfo.ClientAuthentication.Sasl.Iam.Enabled
				}
				f2f0.IAM = f2f0f0
			}
			if resp.ClusterInfo.ClientAuthentication.Sasl.Scram != nil {
				f2f0f1 := &svcapitypes.SCRAM{}
				if resp.ClusterInfo.ClientAuthentication.Sasl.Scram.Enabled != nil {
					f2f0f1.Enabled = resp.ClusterInfo.ClientAuthentication.Sasl.Scram.Enabled
				}
				f2f0.SCRAM = f2f0f1
			}
			f2.SASL = f2f0
		}
		if resp.ClusterInfo.ClientAuthentication.Tls != nil {
			f2f1 := &svcapitypes.TLS{}
			if resp.ClusterInfo.ClientAuthentication.Tls.CertificateAuthorityArnList != nil {
				f2f1.CertificateAuthorityARNList = aws.StringSlice(resp.ClusterInfo.ClientAuthentication.Tls.CertificateAuthorityArnList)
			}
			if resp.ClusterInfo.ClientAuthentication.Tls.Enabled != nil {
				f2f1.Enabled = resp.ClusterInfo.ClientAuthentication.Tls.Enabled
			}
			f2.TLS = f2f1
		}
		if resp.ClusterInfo.ClientAuthentication.Unauthenticated != nil {
			f2f2 := &svcapitypes.Unauthenticated{}
			if resp.ClusterInfo.ClientAuthentication.Unauthenticated.Enabled != nil {
				f2f2.Enabled = resp.ClusterInfo.ClientAuthentication.Unauthenticated.Enabled
			}
			f2.Unauthenticated = f2f2
		}
		ko.Spec.ClientAuthentication = f2
	} else {
		ko.Spec.ClientAuthentication = nil
	}
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.ClusterInfo.ClusterArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.ClusterInfo.ClusterArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.ClusterInfo.ClusterName != nil {
		ko.Spec.Name = resp.ClusterInfo.ClusterName
	} else {
		ko.Spec.Name = nil
	}
	if resp.ClusterInfo.CurrentVersion != nil {
		ko.Status.CurrentVersion = resp.ClusterInfo.CurrentVersion
	} else {
		ko.Status.CurrentVersion = nil
	}
	if resp.ClusterInfo.EncryptionInfo != nil {
		f9 := &svcapitypes.EncryptionInfo{}
		if resp.ClusterInfo.EncryptionInfo.EncryptionAtRest != nil {
			f9f0 := &svcapitypes.EncryptionAtRest{}
			if resp.ClusterInfo.EncryptionInfo.EncryptionAtRest.DataVolumeKMSKeyId != nil {
				f9f0.DataVolumeKMSKeyID = resp.ClusterInfo.EncryptionInfo.EncryptionAtRest.DataVolumeKMSKeyId
			}
			f9.EncryptionAtRest = f9f0
		}
		if resp.ClusterInfo.EncryptionInfo.EncryptionInTransit != nil {
			f9f1 := &svcapitypes.EncryptionInTransit{}
			if resp.ClusterInfo.EncryptionInfo.EncryptionInTransit.ClientBroker != "" {
				f9f1.ClientBroker = aws.String(string(resp.ClusterInfo.EncryptionInfo.EncryptionInTransit.ClientBroker))
			}
			if resp.ClusterInfo.EncryptionInfo.EncryptionInTransit.InCluster != nil {
				f9f1.InCluster = resp.ClusterInfo.EncryptionInfo.EncryptionInTransit.InCluster
			}
			f9.EncryptionInTransit = f9f1
		}
		ko.Spec.EncryptionInfo = f9
	} else {
		ko.Spec.EncryptionInfo = nil
	}
	if resp.ClusterInfo.EnhancedMonitoring != "" {
		ko.Spec.EnhancedMonitoring = aws.String(string(resp.ClusterInfo.EnhancedMonitoring))
	} else {
		ko.Spec.EnhancedMonitoring = nil
	}
	if resp.ClusterInfo.LoggingInfo != nil {
		f11 := &svcapitypes.LoggingInfo{}
		if resp.ClusterInfo.LoggingInfo.BrokerLogs != nil {
			f11f0 := &svcapitypes.BrokerLogs{}
			if resp.ClusterInfo.LoggingInfo.BrokerLogs.CloudWatchLogs != nil {
				f11f0f0 := &svcapitypes.CloudWatchLogs{}
				if resp.ClusterInfo.LoggingInfo.BrokerLogs.CloudWatchLogs.Enabled != nil {
					f11f0f0.Enabled = resp.ClusterInfo.LoggingInfo.BrokerLogs.CloudWatchLogs.Enabled
				}
				if resp.ClusterInfo.LoggingInfo.BrokerLogs.CloudWatchLogs.LogGroup != nil {
					f11f0f0.LogGroup = resp.ClusterInfo.LoggingInfo.BrokerLogs.CloudWatchLogs.LogGroup
				}
				f11f0.CloudWatchLogs = f11f0f0
			}
			if resp.ClusterInfo.LoggingInfo.BrokerLogs.Firehose != nil {
				f11f0f1 := &svcapitypes.Firehose{}
				if resp.ClusterInfo.LoggingInfo.BrokerLogs.Firehose.DeliveryStream != nil {
					f11f0f1.DeliveryStream = resp.ClusterInfo.LoggingInfo.BrokerLogs.Firehose.DeliveryStream
				}
				if resp.ClusterInfo.LoggingInfo.BrokerLogs.Firehose.Enabled != nil {
					f11f0f1.Enabled = resp.ClusterInfo.LoggingInfo.BrokerLogs.Firehose.Enabled
				}
				f11f0.Firehose = f11f0f1
			}
			if resp.ClusterInfo.LoggingInfo.BrokerLogs.S3 != nil {
				f11f0f2 := &svcapitypes.S3{}
				if resp.ClusterInfo.LoggingInfo.BrokerLogs.S3.Bucket != nil {
					f11f0f2.Bucket = resp.ClusterInfo.LoggingInfo.BrokerLogs.S3.Bucket
				}
				if resp.ClusterInfo.LoggingInfo.BrokerLogs.S3.Enabled != nil {
					f11f0f2.Enabled = resp.ClusterInfo.LoggingInfo.BrokerLogs.S3.Enabled
				}
				if resp.ClusterInfo.LoggingInfo.BrokerLogs.S3.Prefix != nil {
					f11f0f2.Prefix = resp.ClusterInfo.LoggingInfo.BrokerLogs.S3.Prefix
				}
				f11f0.S3 = f11f0f2
			}
			f11.BrokerLogs = f11f0
		}
		ko.Spec.LoggingInfo = f11
	} else {
		ko.Spec.LoggingInfo = nil
	}
	if resp.ClusterInfo.NumberOfBrokerNodes != nil {
		numberOfBrokerNodesCopy := int64(*resp.ClusterInfo.NumberOfBrokerNodes)
		ko.Spec.NumberOfBrokerNodes = &numberOfBrokerNodesCopy
	} else {
		ko.Spec.NumberOfBrokerNodes = nil
	}
	if resp.ClusterInfo.OpenMonitoring != nil {
		f13 := &svcapitypes.OpenMonitoringInfo{}
		if resp.ClusterInfo.OpenMonitoring.Prometheus != nil {
			f13f0 := &svcapitypes.PrometheusInfo{}
			if resp.ClusterInfo.OpenMonitoring.Prometheus.JmxExporter != nil {
				f13f0f0 := &svcapitypes.JmxExporterInfo{}
				if resp.ClusterInfo.OpenMonitoring.Prometheus.JmxExporter.EnabledInBroker != nil {
					f13f0f0.EnabledInBroker = resp.ClusterInfo.OpenMonitoring.Prometheus.JmxExporter.EnabledInBroker
				}
				f13f0.JmxExporter = f13f0f0
			}
			if resp.ClusterInfo.OpenMonitoring.Prometheus.NodeExporter != nil {
				f13f0f1 := &svcapitypes.NodeExporterInfo{}
				if resp.ClusterInfo.OpenMonitoring.Prometheus.NodeExporter.EnabledInBroker != nil {
					f13f0f1.EnabledInBroker = resp.ClusterInfo.OpenMonitoring.Prometheus.NodeExporter.EnabledInBroker
				}
				f13f0.NodeExporter = f13f0f1
			}
			f13.Prometheus = f13f0
		}
		ko.Spec.OpenMonitoring = f13
	} else {
		ko.Spec.OpenMonitoring = nil
	}
	if resp.ClusterInfo.State != "" {
		ko.Status.State = aws.String(string(resp.ClusterInfo.State))
	} else {
		ko.Status.State = nil
	}
	if resp.ClusterInfo.StorageMode != "" {
		ko.Spec.StorageMode = aws.String(string(resp.ClusterInfo.StorageMode))
	} else {
		ko.Spec.StorageMode = nil
	}
	if resp.ClusterInfo.Tags != nil {
		ko.Spec.Tags = aws.StringMap(resp.ClusterInfo.Tags)
	} else {
		ko.Spec.Tags = nil
	}
	if resp.ClusterInfo.ZookeeperConnectString != nil {
		ko.Status.ZookeeperConnectString = resp.ClusterInfo.ZookeeperConnectString
	} else {
		ko.Status.ZookeeperConnectString = nil
	}
	if resp.ClusterInfo.ZookeeperConnectStringTls != nil {
		ko.Status.ZookeeperConnectStringTLS = resp.ClusterInfo.ZookeeperConnectStringTls
	} else {
		ko.Status.ZookeeperConnectStringTLS = nil
	}

	rm.setStatusDefaults(ko)
	if resp.ClusterInfo.CurrentVersion != nil {
		ko.Status.CurrentVersion = resp.ClusterInfo.CurrentVersion
	} else {
		ko.Status.CurrentVersion = nil
	}
	if !clusterActive(&resource{ko}) {
		// Setting resource synced condition to false will trigger a requeue of
		// the resource. No need to return a requeue error here.
		ackcondition.SetSynced(&resource{ko}, corev1.ConditionFalse, nil, nil)
	} else {
		ackcondition.SetSynced(&resource{ko}, corev1.ConditionTrue, nil, nil)
		ko.Spec.AssociatedSCRAMSecrets, err = rm.getAssociatedScramSecrets(ctx, &resource{ko})
		if err != nil {
			return nil, err
		}
		err = rm.setResourceAdditionalFields(ctx, ko)
		if err != nil {
			return nil, err
		}
	}
	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadOneInput returns true if there are any fields
// for the ReadOne Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadOneInput(
	r *resource,
) bool {
	return (r.ko.Status.ACKResourceMetadata == nil || r.ko.Status.ACKResourceMetadata.ARN == nil)

}

// newDescribeRequestPayload returns SDK-specific struct for the HTTP request
// payload of the Describe API call for the resource
func (rm *resourceManager) newDescribeRequestPayload(
	r *resource,
) (*svcsdk.DescribeClusterInput, error) {
	res := &svcsdk.DescribeClusterInput{}

	if r.ko.Status.ACKResourceMetadata != nil && r.ko.Status.ACKResourceMetadata.ARN != nil {
		res.ClusterArn = (*string)(r.ko.Status.ACKResourceMetadata.ARN)
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateClusterOutput
	_ = resp
	resp, err = rm.sdkapi.CreateCluster(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateCluster", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.ClusterArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.ClusterArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.ClusterName != nil {
		ko.Spec.Name = resp.ClusterName
	} else {
		ko.Spec.Name = nil
	}
	if resp.State != "" {
		ko.Status.State = aws.String(string(resp.State))
	} else {
		ko.Status.State = nil
	}

	rm.setStatusDefaults(ko)
	if !clusterActive(&resource{ko}) {
		// This causes a requeue and scram secrets will be synced on the next
		// reconciliation loop
		ackcondition.SetSynced(&resource{ko}, corev1.ConditionFalse, nil, nil)
		return &resource{ko}, nil
	}
	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateClusterInput, error) {
	res := &svcsdk.CreateClusterInput{}

	if r.ko.Spec.BrokerNodeGroupInfo != nil {
		f0 := &svcsdktypes.BrokerNodeGroupInfo{}
		if r.ko.Spec.BrokerNodeGroupInfo.BrokerAZDistribution != nil {
			f0.BrokerAZDistribution = svcsdktypes.BrokerAZDistribution(*r.ko.Spec.BrokerNodeGroupInfo.BrokerAZDistribution)
		}
		if r.ko.Spec.BrokerNodeGroupInfo.ClientSubnets != nil {
			f0.ClientSubnets = aws.ToStringSlice(r.ko.Spec.BrokerNodeGroupInfo.ClientSubnets)
		}
		if r.ko.Spec.BrokerNodeGroupInfo.ConnectivityInfo != nil {
			f0f2 := &svcsdktypes.ConnectivityInfo{}
			if r.ko.Spec.BrokerNodeGroupInfo.ConnectivityInfo.PublicAccess != nil {
				f0f2f0 := &svcsdktypes.PublicAccess{}
				if r.ko.Spec.BrokerNodeGroupInfo.ConnectivityInfo.PublicAccess.Type != nil {
					f0f2f0.Type = r.ko.Spec.BrokerNodeGroupInfo.ConnectivityInfo.PublicAccess.Type
				}
				f0f2.PublicAccess = f0f2f0
			}
			f0.ConnectivityInfo = f0f2
		}
		if r.ko.Spec.BrokerNodeGroupInfo.InstanceType != nil {
			f0.InstanceType = r.ko.Spec.BrokerNodeGroupInfo.InstanceType
		}
		if r.ko.Spec.BrokerNodeGroupInfo.SecurityGroups != nil {
			f0.SecurityGroups = aws.ToStringSlice(r.ko.Spec.BrokerNodeGroupInfo.SecurityGroups)
		}
		if r.ko.Spec.BrokerNodeGroupInfo.StorageInfo != nil {
			f0f5 := &svcsdktypes.StorageInfo{}
			if r.ko.Spec.BrokerNodeGroupInfo.StorageInfo.EBSStorageInfo != nil {
				f0f5f0 := &svcsdktypes.EBSStorageInfo{}
				if r.ko.Spec.BrokerNodeGroupInfo.StorageInfo.EBSStorageInfo.ProvisionedThroughput != nil {
					f0f5f0f0 := &svcsdktypes.ProvisionedThroughput{}
					if r.ko.Spec.BrokerNodeGroupInfo.StorageInfo.EBSStorageInfo.ProvisionedThroughput.Enabled != nil {
						f0f5f0f0.Enabled = r.ko.Spec.BrokerNodeGroupInfo.StorageInfo.EBSStorageInfo.ProvisionedThroughput.Enabled
					}
					if r.ko.Spec.BrokerNodeGroupInfo.StorageInfo.EBSStorageInfo.ProvisionedThroughput.VolumeThroughput != nil {
						volumeThroughputCopy0 := *r.ko.Spec.BrokerNodeGroupInfo.StorageInfo.EBSStorageInfo.ProvisionedThroughput.VolumeThroughput
						if volumeThroughputCopy0 > math.MaxInt32 || volumeThroughputCopy0 < math.MinInt32 {
							return nil, fmt.Errorf("error: field VolumeThroughput is of type int32")
						}
						volumeThroughputCopy := int32(volumeThroughputCopy0)
						f0f5f0f0.VolumeThroughput = &volumeThroughputCopy
					}
					f0f5f0.ProvisionedThroughput = f0f5f0f0
				}
				if r.ko.Spec.BrokerNodeGroupInfo.StorageInfo.EBSStorageInfo.VolumeSize != nil {
					volumeSizeCopy0 := *r.ko.Spec.BrokerNodeGroupInfo.StorageInfo.EBSStorageInfo.VolumeSize
					if volumeSizeCopy0 > math.MaxInt32 || volumeSizeCopy0 < math.MinInt32 {
						return nil, fmt.Errorf("error: field VolumeSize is of type int32")
					}
					volumeSizeCopy := int32(volumeSizeCopy0)
					f0f5f0.VolumeSize = &volumeSizeCopy
				}
				f0f5.EbsStorageInfo = f0f5f0
			}
			f0.StorageInfo = f0f5
		}
		res.BrokerNodeGroupInfo = f0
	}
	if r.ko.Spec.ClientAuthentication != nil {
		f1 := &svcsdktypes.ClientAuthentication{}
		if r.ko.Spec.ClientAuthentication.SASL != nil {
			f1f0 := &svcsdktypes.Sasl{}
			if r.ko.Spec.ClientAuthentication.SASL.IAM != nil {
				f1f0f0 := &svcsdktypes.Iam{}
				if r.ko.Spec.ClientAuthentication.SASL.IAM.Enabled != nil {
					f1f0f0.Enabled = r.ko.Spec.ClientAuthentication.SASL.IAM.Enabled
				}
				f1f0.Iam = f1f0f0
			}
			if r.ko.Spec.ClientAuthentication.SASL.SCRAM != nil {
				f1f0f1 := &svcsdktypes.Scram{}
				if r.ko.Spec.ClientAuthentication.SASL.SCRAM.Enabled != nil {
					f1f0f1.Enabled = r.ko.Spec.ClientAuthentication.SASL.SCRAM.Enabled
				}
				f1f0.Scram = f1f0f1
			}
			f1.Sasl = f1f0
		}
		if r.ko.Spec.ClientAuthentication.TLS != nil {
			f1f1 := &svcsdktypes.Tls{}
			if r.ko.Spec.ClientAuthentication.TLS.CertificateAuthorityARNList != nil {
				f1f1.CertificateAuthorityArnList = aws.ToStringSlice(r.ko.Spec.ClientAuthentication.TLS.CertificateAuthorityARNList)
			}
			if r.ko.Spec.ClientAuthentication.TLS.Enabled != nil {
				f1f1.Enabled = r.ko.Spec.ClientAuthentication.TLS.Enabled
			}
			f1.Tls = f1f1
		}
		if r.ko.Spec.ClientAuthentication.Unauthenticated != nil {
			f1f2 := &svcsdktypes.Unauthenticated{}
			if r.ko.Spec.ClientAuthentication.Unauthenticated.Enabled != nil {
				f1f2.Enabled = r.ko.Spec.ClientAuthentication.Unauthenticated.Enabled
			}
			f1.Unauthenticated = f1f2
		}
		res.ClientAuthentication = f1
	}
	if r.ko.Spec.Name != nil {
		res.ClusterName = r.ko.Spec.Name
	}
	if r.ko.Spec.ConfigurationInfo != nil {
		f3 := &svcsdktypes.ConfigurationInfo{}
		if r.ko.Spec.ConfigurationInfo.ARN != nil {
			f3.Arn = r.ko.Spec.ConfigurationInfo.ARN
		}
		if r.ko.Spec.ConfigurationInfo.Revision != nil {
			f3.Revision = r.ko.Spec.ConfigurationInfo.Revision
		}
		res.ConfigurationInfo = f3
	}
	if r.ko.Spec.EncryptionInfo != nil {
		f4 := &svcsdktypes.EncryptionInfo{}
		if r.ko.Spec.EncryptionInfo.EncryptionAtRest != nil {
			f4f0 := &svcsdktypes.EncryptionAtRest{}
			if r.ko.Spec.EncryptionInfo.EncryptionAtRest.DataVolumeKMSKeyID != nil {
				f4f0.DataVolumeKMSKeyId = r.ko.Spec.EncryptionInfo.EncryptionAtRest.DataVolumeKMSKeyID
			}
			f4.EncryptionAtRest = f4f0
		}
		if r.ko.Spec.EncryptionInfo.EncryptionInTransit != nil {
			f4f1 := &svcsdktypes.EncryptionInTransit{}
			if r.ko.Spec.EncryptionInfo.EncryptionInTransit.ClientBroker != nil {
				f4f1.ClientBroker = svcsdktypes.ClientBroker(*r.ko.Spec.EncryptionInfo.EncryptionInTransit.ClientBroker)
			}
			if r.ko.Spec.EncryptionInfo.EncryptionInTransit.InCluster != nil {
				f4f1.InCluster = r.ko.Spec.EncryptionInfo.EncryptionInTransit.InCluster
			}
			f4.EncryptionInTransit = f4f1
		}
		res.EncryptionInfo = f4
	}
	if r.ko.Spec.EnhancedMonitoring != nil {
		res.EnhancedMonitoring = svcsdktypes.EnhancedMonitoring(*r.ko.Spec.EnhancedMonitoring)
	}
	if r.ko.Spec.KafkaVersion != nil {
		res.KafkaVersion = r.ko.Spec.KafkaVersion
	}
	if r.ko.Spec.LoggingInfo != nil {
		f7 := &svcsdktypes.LoggingInfo{}
		if r.ko.Spec.LoggingInfo.BrokerLogs != nil {
			f7f0 := &svcsdktypes.BrokerLogs{}
			if r.ko.Spec.LoggingInfo.BrokerLogs.CloudWatchLogs != nil {
				f7f0f0 := &svcsdktypes.CloudWatchLogs{}
				if r.ko.Spec.LoggingInfo.BrokerLogs.CloudWatchLogs.Enabled != nil {
					f7f0f0.Enabled = r.ko.Spec.LoggingInfo.BrokerLogs.CloudWatchLogs.Enabled
				}
				if r.ko.Spec.LoggingInfo.BrokerLogs.CloudWatchLogs.LogGroup != nil {
					f7f0f0.LogGroup = r.ko.Spec.LoggingInfo.BrokerLogs.CloudWatchLogs.LogGroup
				}
				f7f0.CloudWatchLogs = f7f0f0
			}
			if r.ko.Spec.LoggingInfo.BrokerLogs.Firehose != nil {
				f7f0f1 := &svcsdktypes.Firehose{}
				if r.ko.Spec.LoggingInfo.BrokerLogs.Firehose.DeliveryStream != nil {
					f7f0f1.DeliveryStream = r.ko.Spec.LoggingInfo.BrokerLogs.Firehose.DeliveryStream
				}
				if r.ko.Spec.LoggingInfo.BrokerLogs.Firehose.Enabled != nil {
					f7f0f1.Enabled = r.ko.Spec.LoggingInfo.BrokerLogs.Firehose.Enabled
				}
				f7f0.Firehose = f7f0f1
			}
			if r.ko.Spec.LoggingInfo.BrokerLogs.S3 != nil {
				f7f0f2 := &svcsdktypes.S3{}
				if r.ko.Spec.LoggingInfo.BrokerLogs.S3.Bucket != nil {
					f7f0f2.Bucket = r.ko.Spec.LoggingInfo.BrokerLogs.S3.Bucket
				}
				if r.ko.Spec.LoggingInfo.BrokerLogs.S3.Enabled != nil {
					f7f0f2.Enabled = r.ko.Spec.LoggingInfo.BrokerLogs.S3.Enabled
				}
				if r.ko.Spec.LoggingInfo.BrokerLogs.S3.Prefix != nil {
					f7f0f2.Prefix = r.ko.Spec.LoggingInfo.BrokerLogs.S3.Prefix
				}
				f7f0.S3 = f7f0f2
			}
			f7.BrokerLogs = f7f0
		}
		res.LoggingInfo = f7
	}
	if r.ko.Spec.NumberOfBrokerNodes != nil {
		numberOfBrokerNodesCopy0 := *r.ko.Spec.NumberOfBrokerNodes
		if numberOfBrokerNodesCopy0 > math.MaxInt32 || numberOfBrokerNodesCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field NumberOfBrokerNodes is of type int32")
		}
		numberOfBrokerNodesCopy := int32(numberOfBrokerNodesCopy0)
		res.NumberOfBrokerNodes = &numberOfBrokerNodesCopy
	}
	if r.ko.Spec.OpenMonitoring != nil {
		f9 := &svcsdktypes.OpenMonitoringInfo{}
		if r.ko.Spec.OpenMonitoring.Prometheus != nil {
			f9f0 := &svcsdktypes.PrometheusInfo{}
			if r.ko.Spec.OpenMonitoring.Prometheus.JmxExporter != nil {
				f9f0f0 := &svcsdktypes.JmxExporterInfo{}
				if r.ko.Spec.OpenMonitoring.Prometheus.JmxExporter.EnabledInBroker != nil {
					f9f0f0.EnabledInBroker = r.ko.Spec.OpenMonitoring.Prometheus.JmxExporter.EnabledInBroker
				}
				f9f0.JmxExporter = f9f0f0
			}
			if r.ko.Spec.OpenMonitoring.Prometheus.NodeExporter != nil {
				f9f0f1 := &svcsdktypes.NodeExporterInfo{}
				if r.ko.Spec.OpenMonitoring.Prometheus.NodeExporter.EnabledInBroker != nil {
					f9f0f1.EnabledInBroker = r.ko.Spec.OpenMonitoring.Prometheus.NodeExporter.EnabledInBroker
				}
				f9f0.NodeExporter = f9f0f1
			}
			f9.Prometheus = f9f0
		}
		res.OpenMonitoring = f9
	}
	if r.ko.Spec.StorageMode != nil {
		res.StorageMode = svcsdktypes.StorageMode(*r.ko.Spec.StorageMode)
	}
	if r.ko.Spec.Tags != nil {
		res.Tags = aws.ToStringMap(r.ko.Spec.Tags)
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (*resource, error) {
	return rm.customUpdate(ctx, desired, latest, delta)
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	if clusterDeleting(r) {
		return nil, requeueWaitWhileDeleting
	}
	if clusterCreating(r) {
		return nil, requeueWaitWhileCreating
	}
	groupCpy := r.ko.DeepCopy()
	groupCpy.Spec.AssociatedSCRAMSecrets = nil
	if err := rm.syncAssociatedScramSecrets(ctx, &resource{ko: groupCpy}, r); err != nil {
		return nil, err
	}
	if !clusterActive(r) {
		// doing this to avoid BadRequestException
		return r, ackrequeue.NeededAfter(
			fmt.Errorf("waiting for cluster to be active before deletion"),
			ackrequeue.DefaultRequeueAfterDuration,
		)
	}

	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteClusterOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteCluster(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteCluster", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteClusterInput, error) {
	res := &svcsdk.DeleteClusterInput{}

	if r.ko.Status.ACKResourceMetadata != nil && r.ko.Status.ACKResourceMetadata.ARN != nil {
		res.ClusterArn = (*string)(r.ko.Status.ACKResourceMetadata.ARN)
	}
	if r.ko.Status.CurrentVersion != nil {
		res.CurrentVersion = r.ko.Status.CurrentVersion
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.Cluster,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}

	var terminalErr smithy.APIError
	if !errors.As(err, &terminalErr) {
		return false
	}
	switch terminalErr.ErrorCode() {
	case "BadRequestException":
		return true
	default:
		return false
	}
}
