// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	"github.com/aws/aws-sdk-go/aws"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = &aws.JSONValue{}
	_ = ackv1alpha1.AWSAccountID("")
)

// Details of an Amazon MSK Cluster.
type AmazonMskCluster struct {
	MskClusterARN *string `json:"mskClusterARN,omitempty"`
}

// Specifies the EBS volume upgrade information. The broker identifier must
// be set to the keyword ALL. This means the changes apply to all the brokers
// in the cluster.
type BrokerEBSVolumeInfo struct {
	KafkaBrokerNodeID *string `json:"kafkaBrokerNodeID,omitempty"`
	// Contains information about provisioned throughput for EBS storage volumes
	// attached to kafka broker nodes.
	ProvisionedThroughput *ProvisionedThroughput `json:"provisionedThroughput,omitempty"`
	VolumeSizeGB          *int64                 `json:"volumeSizeGB,omitempty"`
}

type BrokerLogs struct {
	CloudWatchLogs *CloudWatchLogs `json:"cloudWatchLogs,omitempty"`
	Firehose       *Firehose       `json:"firehose,omitempty"`
	S3             *S3             `json:"s3,omitempty"`
}

// Describes the setup to be used for Apache Kafka broker nodes in the cluster.
type BrokerNodeGroupInfo struct {
	// The distribution of broker nodes across Availability Zones. This is an optional
	// parameter. If you don't specify it, Amazon MSK gives it the value DEFAULT.
	// You can also explicitly set this parameter to the value DEFAULT. No other
	// values are currently allowed.
	//
	// Amazon MSK distributes the broker nodes evenly across the Availability Zones
	// that correspond to the subnets you provide when you create the cluster.
	BrokerAZDistribution *string   `json:"brokerAZDistribution,omitempty"`
	ClientSubnets        []*string `json:"clientSubnets,omitempty"`
	// Information about the broker access configuration.
	ConnectivityInfo *ConnectivityInfo `json:"connectivityInfo,omitempty"`
	InstanceType     *string           `json:"instanceType,omitempty"`
	SecurityGroups   []*string         `json:"securityGroups,omitempty"`
	// Contains information about storage volumes attached to MSK broker nodes.
	StorageInfo *StorageInfo `json:"storageInfo,omitempty"`
}

// BrokerNodeInfo
type BrokerNodeInfo struct {
	AttachedENIID      *string `json:"attachedENIID,omitempty"`
	ClientSubnet       *string `json:"clientSubnet,omitempty"`
	ClientVPCIPAddress *string `json:"clientVPCIPAddress,omitempty"`
	// Information about the current software installed on the cluster.
	CurrentBrokerSoftwareInfo *BrokerSoftwareInfo `json:"currentBrokerSoftwareInfo,omitempty"`
	Endpoints                 []*string           `json:"endpoints,omitempty"`
}

// Information about the current software installed on the cluster.
type BrokerSoftwareInfo struct {
	ConfigurationARN      *string `json:"configurationARN,omitempty"`
	ConfigurationRevision *int64  `json:"configurationRevision,omitempty"`
	KafkaVersion          *string `json:"kafkaVersion,omitempty"`
}

// Includes all client authentication information.
type ClientAuthentication struct {
	// Details for client authentication using SASL.
	SASL *SASL `json:"sasl,omitempty"`
	// Details for client authentication using TLS.
	TLS             *TLS             `json:"tls,omitempty"`
	Unauthenticated *Unauthenticated `json:"unauthenticated,omitempty"`
}

// The client VPC connection object.
type ClientVPCConnection struct {
	Authentication   *string      `json:"authentication,omitempty"`
	CreationTime     *metav1.Time `json:"creationTime,omitempty"`
	Owner            *string      `json:"owner,omitempty"`
	VPCConnectionARN *string      `json:"vpcConnectionARN,omitempty"`
}

type CloudWatchLogs struct {
	Enabled  *bool   `json:"enabled,omitempty"`
	LogGroup *string `json:"logGroup,omitempty"`
}

// Returns information about a cluster.
type ClusterInfo struct {
	ActiveOperationARN *string `json:"activeOperationARN,omitempty"`
	// Describes the setup to be used for Apache Kafka broker nodes in the cluster.
	BrokerNodeGroupInfo *BrokerNodeGroupInfo `json:"brokerNodeGroupInfo,omitempty"`
	// Includes all client authentication information.
	ClientAuthentication *ClientAuthentication `json:"clientAuthentication,omitempty"`
	ClusterARN           *string               `json:"clusterARN,omitempty"`
	ClusterName          *string               `json:"clusterName,omitempty"`
	CreationTime         *metav1.Time          `json:"creationTime,omitempty"`
	// Information about the current software installed on the cluster.
	CurrentBrokerSoftwareInfo *BrokerSoftwareInfo `json:"currentBrokerSoftwareInfo,omitempty"`
	CurrentVersion            *string             `json:"currentVersion,omitempty"`
	// A type of an action required from the customer.
	CustomerActionStatus *string `json:"customerActionStatus,omitempty"`
	// Includes encryption-related information, such as the AWS KMS key used for
	// encrypting data at rest and whether you want MSK to encrypt your data in
	// transit.
	EncryptionInfo *EncryptionInfo `json:"encryptionInfo,omitempty"`
	// Specifies which metrics are gathered for the MSK cluster. This property has
	// the following possible values: DEFAULT, PER_BROKER, PER_TOPIC_PER_BROKER,
	// and PER_TOPIC_PER_PARTITION. For a list of the metrics associated with each
	// of these levels of monitoring, see Monitoring (https://docs.aws.amazon.com/msk/latest/developerguide/monitoring.html).
	EnhancedMonitoring  *string      `json:"enhancedMonitoring,omitempty"`
	LoggingInfo         *LoggingInfo `json:"loggingInfo,omitempty"`
	NumberOfBrokerNodes *int64       `json:"numberOfBrokerNodes,omitempty"`
	// JMX and Node monitoring for the MSK cluster.
	OpenMonitoring *OpenMonitoring `json:"openMonitoring,omitempty"`
	// The state of the Apache Kafka cluster.
	State     *string    `json:"state,omitempty"`
	StateInfo *StateInfo `json:"stateInfo,omitempty"`
	// Controls storage mode for various supported storage tiers.
	StorageMode               *string            `json:"storageMode,omitempty"`
	Tags                      map[string]*string `json:"tags,omitempty"`
	ZookeeperConnectString    *string            `json:"zookeeperConnectString,omitempty"`
	ZookeeperConnectStringTLS *string            `json:"zookeeperConnectStringTLS,omitempty"`
}

// Returns information about a cluster operation.
type ClusterOperationInfo struct {
	ClientRequestID *string      `json:"clientRequestID,omitempty"`
	ClusterARN      *string      `json:"clusterARN,omitempty"`
	CreationTime    *metav1.Time `json:"creationTime,omitempty"`
	EndTime         *metav1.Time `json:"endTime,omitempty"`
	OperationARN    *string      `json:"operationARN,omitempty"`
	OperationState  *string      `json:"operationState,omitempty"`
	OperationType   *string      `json:"operationType,omitempty"`
}

// Step taken during a cluster operation.
type ClusterOperationStep struct {
	StepName *string `json:"stepName,omitempty"`
}

// State information about the operation step.
type ClusterOperationStepInfo struct {
	StepStatus *string `json:"stepStatus,omitempty"`
}

// Returns information about a cluster operation.
type ClusterOperationV2 struct {
	ClusterARN     *string      `json:"clusterARN,omitempty"`
	EndTime        *metav1.Time `json:"endTime,omitempty"`
	OperationARN   *string      `json:"operationARN,omitempty"`
	OperationState *string      `json:"operationState,omitempty"`
	OperationType  *string      `json:"operationType,omitempty"`
	StartTime      *metav1.Time `json:"startTime,omitempty"`
}

// Returns information about a cluster operation.
type ClusterOperationV2Summary struct {
	ClusterARN     *string      `json:"clusterARN,omitempty"`
	EndTime        *metav1.Time `json:"endTime,omitempty"`
	OperationARN   *string      `json:"operationARN,omitempty"`
	OperationState *string      `json:"operationState,omitempty"`
	OperationType  *string      `json:"operationType,omitempty"`
	StartTime      *metav1.Time `json:"startTime,omitempty"`
}

// Returns information about a cluster.
type Cluster_SDK struct {
	ActiveOperationARN *string      `json:"activeOperationARN,omitempty"`
	ClusterARN         *string      `json:"clusterARN,omitempty"`
	ClusterName        *string      `json:"clusterName,omitempty"`
	CreationTime       *metav1.Time `json:"creationTime,omitempty"`
	CurrentVersion     *string      `json:"currentVersion,omitempty"`
	// The state of the Apache Kafka cluster.
	State     *string            `json:"state,omitempty"`
	StateInfo *StateInfo         `json:"stateInfo,omitempty"`
	Tags      map[string]*string `json:"tags,omitempty"`
}

// Contains source Apache Kafka versions and compatible target Apache Kafka
// versions.
type CompatibleKafkaVersion struct {
	SourceVersion  *string   `json:"sourceVersion,omitempty"`
	TargetVersions []*string `json:"targetVersions,omitempty"`
}

// Specifies the configuration to use for the brokers.
type ConfigurationInfo struct {
	ARN      *string `json:"arn,omitempty"`
	Revision *int64  `json:"revision,omitempty"`
}

// Describes a configuration revision.
type ConfigurationRevision struct {
	CreationTime *metav1.Time `json:"creationTime,omitempty"`
	Description  *string      `json:"description,omitempty"`
	Revision     *int64       `json:"revision,omitempty"`
}

// Represents an MSK Configuration.
type Configuration_SDK struct {
	ARN           *string      `json:"arn,omitempty"`
	CreationTime  *metav1.Time `json:"creationTime,omitempty"`
	Description   *string      `json:"description,omitempty"`
	KafkaVersions []*string    `json:"kafkaVersions,omitempty"`
	// Describes a configuration revision.
	LatestRevision *ConfigurationRevision `json:"latestRevision,omitempty"`
	Name           *string                `json:"name,omitempty"`
	// The state of a configuration.
	State *string `json:"state,omitempty"`
}

// Information about the broker access configuration.
type ConnectivityInfo struct {
	// Public access control for brokers.
	PublicAccess *PublicAccess `json:"publicAccess,omitempty"`
}

// Details about consumer group replication.
type ConsumerGroupReplication struct {
	DetectAndCopyNewConsumerGroups  *bool `json:"detectAndCopyNewConsumerGroups,omitempty"`
	SynchroniseConsumerGroupOffsets *bool `json:"synchroniseConsumerGroupOffsets,omitempty"`
}

// Details about consumer group replication.
type ConsumerGroupReplicationUpdate struct {
	DetectAndCopyNewConsumerGroups  *bool `json:"detectAndCopyNewConsumerGroups,omitempty"`
	SynchroniseConsumerGroupOffsets *bool `json:"synchroniseConsumerGroupOffsets,omitempty"`
}

// Controller node information.
type ControllerNodeInfo struct {
	Endpoints []*string `json:"endpoints,omitempty"`
}

// Contains information about the EBS storage volumes attached to Apache Kafka
// broker nodes.
type EBSStorageInfo struct {
	// Contains information about provisioned throughput for EBS storage volumes
	// attached to kafka broker nodes.
	ProvisionedThroughput *ProvisionedThroughput `json:"provisionedThroughput,omitempty"`
	VolumeSize            *int64                 `json:"volumeSize,omitempty"`
}

// The data-volume encryption details.
type EncryptionAtRest struct {
	DataVolumeKMSKeyID *string `json:"dataVolumeKMSKeyID,omitempty"`
}

// The settings for encrypting data in transit.
type EncryptionInTransit struct {
	// Client-broker encryption in transit setting.
	ClientBroker *string `json:"clientBroker,omitempty"`
	InCluster    *bool   `json:"inCluster,omitempty"`
}

// Includes encryption-related information, such as the AWS KMS key used for
// encrypting data at rest and whether you want MSK to encrypt your data in
// transit.
type EncryptionInfo struct {
	// The data-volume encryption details.
	EncryptionAtRest *EncryptionAtRest `json:"encryptionAtRest,omitempty"`
	// The settings for encrypting data in transit.
	EncryptionInTransit *EncryptionInTransit `json:"encryptionInTransit,omitempty"`
}

// Returns information about an error state of the cluster.
type ErrorInfo struct {
	ErrorCode   *string `json:"errorCode,omitempty"`
	ErrorString *string `json:"errorString,omitempty"`
}

type Firehose struct {
	DeliveryStream *string `json:"deliveryStream,omitempty"`
	Enabled        *bool   `json:"enabled,omitempty"`
}

// Details for IAM access control.
type IAM struct {
	Enabled *bool `json:"enabled,omitempty"`
}

// Indicates whether you want to turn on or turn off the JMX Exporter.
type JmxExporter struct {
	EnabledInBroker *bool `json:"enabledInBroker,omitempty"`
}

// Indicates whether you want to turn on or turn off the JMX Exporter.
type JmxExporterInfo struct {
	EnabledInBroker *bool `json:"enabledInBroker,omitempty"`
}

// Details of an Amazon VPC which has network connectivity to the Apache Kafka
// cluster.
type KafkaClusterClientVPCConfig struct {
	SecurityGroupIDs []*string `json:"securityGroupIDs,omitempty"`
	SubnetIDs        []*string `json:"subnetIDs,omitempty"`
}

// Information about Kafka Cluster used as source / target for replication.
type KafkaClusterDescription struct {
	KafkaClusterAlias *string `json:"kafkaClusterAlias,omitempty"`
}

// Summarized information about Kafka Cluster used as source / target for replication.
type KafkaClusterSummary struct {
	KafkaClusterAlias *string `json:"kafkaClusterAlias,omitempty"`
}

type KafkaVersion struct {
	Version *string `json:"version,omitempty"`
}

type LoggingInfo struct {
	BrokerLogs *BrokerLogs `json:"brokerLogs,omitempty"`
}

// Information about cluster attributes that can be updated via update APIs.
type MutableClusterInfo struct {
	// Includes all client authentication information.
	ClientAuthentication *ClientAuthentication `json:"clientAuthentication,omitempty"`
	// Specifies the configuration to use for the brokers.
	ConfigurationInfo *ConfigurationInfo `json:"configurationInfo,omitempty"`
	// Information about the broker access configuration.
	ConnectivityInfo *ConnectivityInfo `json:"connectivityInfo,omitempty"`
	// Includes encryption-related information, such as the AWS KMS key used for
	// encrypting data at rest and whether you want MSK to encrypt your data in
	// transit.
	EncryptionInfo *EncryptionInfo `json:"encryptionInfo,omitempty"`
	// Specifies which metrics are gathered for the MSK cluster. This property has
	// the following possible values: DEFAULT, PER_BROKER, PER_TOPIC_PER_BROKER,
	// and PER_TOPIC_PER_PARTITION. For a list of the metrics associated with each
	// of these levels of monitoring, see Monitoring (https://docs.aws.amazon.com/msk/latest/developerguide/monitoring.html).
	EnhancedMonitoring  *string      `json:"enhancedMonitoring,omitempty"`
	InstanceType        *string      `json:"instanceType,omitempty"`
	KafkaVersion        *string      `json:"kafkaVersion,omitempty"`
	LoggingInfo         *LoggingInfo `json:"loggingInfo,omitempty"`
	NumberOfBrokerNodes *int64       `json:"numberOfBrokerNodes,omitempty"`
	// JMX and Node monitoring for the MSK cluster.
	OpenMonitoring *OpenMonitoring `json:"openMonitoring,omitempty"`
	// Controls storage mode for various supported storage tiers.
	StorageMode *string `json:"storageMode,omitempty"`
}

// Indicates whether you want to turn on or turn off the Node Exporter.
type NodeExporter struct {
	EnabledInBroker *bool `json:"enabledInBroker,omitempty"`
}

// Indicates whether you want to turn on or turn off the Node Exporter.
type NodeExporterInfo struct {
	EnabledInBroker *bool `json:"enabledInBroker,omitempty"`
}

// The node information object.
type NodeInfo struct {
	AddedToClusterTime *string `json:"addedToClusterTime,omitempty"`
	InstanceType       *string `json:"instanceType,omitempty"`
	NodeARN            *string `json:"nodeARN,omitempty"`
}

// JMX and Node monitoring for the MSK cluster.
type OpenMonitoring struct {
	// Prometheus settings.
	Prometheus *Prometheus `json:"prometheus,omitempty"`
}

// JMX and Node monitoring for the MSK cluster.
type OpenMonitoringInfo struct {
	// Prometheus settings.
	Prometheus *PrometheusInfo `json:"prometheus,omitempty"`
}

// Prometheus settings.
type Prometheus struct {
	// Indicates whether you want to turn on or turn off the JMX Exporter.
	JmxExporter *JmxExporter `json:"jmxExporter,omitempty"`
	// Indicates whether you want to turn on or turn off the Node Exporter.
	NodeExporter *NodeExporter `json:"nodeExporter,omitempty"`
}

// Prometheus settings.
type PrometheusInfo struct {
	// Indicates whether you want to turn on or turn off the JMX Exporter.
	JmxExporter *JmxExporterInfo `json:"jmxExporter,omitempty"`
	// Indicates whether you want to turn on or turn off the Node Exporter.
	NodeExporter *NodeExporterInfo `json:"nodeExporter,omitempty"`
}

// Provisioned cluster.
type Provisioned struct {
	// Describes the setup to be used for Apache Kafka broker nodes in the cluster.
	BrokerNodeGroupInfo *BrokerNodeGroupInfo `json:"brokerNodeGroupInfo,omitempty"`
	// Includes all client authentication information.
	ClientAuthentication *ClientAuthentication `json:"clientAuthentication,omitempty"`
	// Information about the current software installed on the cluster.
	CurrentBrokerSoftwareInfo *BrokerSoftwareInfo `json:"currentBrokerSoftwareInfo,omitempty"`
	// A type of an action required from the customer.
	CustomerActionStatus *string `json:"customerActionStatus,omitempty"`
	// Includes encryption-related information, such as the AWS KMS key used for
	// encrypting data at rest and whether you want MSK to encrypt your data in
	// transit.
	EncryptionInfo *EncryptionInfo `json:"encryptionInfo,omitempty"`
	// Specifies which metrics are gathered for the MSK cluster. This property has
	// the following possible values: DEFAULT, PER_BROKER, PER_TOPIC_PER_BROKER,
	// and PER_TOPIC_PER_PARTITION. For a list of the metrics associated with each
	// of these levels of monitoring, see Monitoring (https://docs.aws.amazon.com/msk/latest/developerguide/monitoring.html).
	EnhancedMonitoring  *string      `json:"enhancedMonitoring,omitempty"`
	LoggingInfo         *LoggingInfo `json:"loggingInfo,omitempty"`
	NumberOfBrokerNodes *int64       `json:"numberOfBrokerNodes,omitempty"`
	// JMX and Node monitoring for the MSK cluster.
	OpenMonitoring *OpenMonitoringInfo `json:"openMonitoring,omitempty"`
	// Controls storage mode for various supported storage tiers.
	StorageMode               *string `json:"storageMode,omitempty"`
	ZookeeperConnectString    *string `json:"zookeeperConnectString,omitempty"`
	ZookeeperConnectStringTLS *string `json:"zookeeperConnectStringTLS,omitempty"`
}

// Provisioned cluster request.
type ProvisionedRequest struct {
	// Describes the setup to be used for Apache Kafka broker nodes in the cluster.
	BrokerNodeGroupInfo *BrokerNodeGroupInfo `json:"brokerNodeGroupInfo,omitempty"`
	// Includes all client authentication information.
	ClientAuthentication *ClientAuthentication `json:"clientAuthentication,omitempty"`
	// Specifies the configuration to use for the brokers.
	ConfigurationInfo *ConfigurationInfo `json:"configurationInfo,omitempty"`
	// Includes encryption-related information, such as the AWS KMS key used for
	// encrypting data at rest and whether you want MSK to encrypt your data in
	// transit.
	EncryptionInfo *EncryptionInfo `json:"encryptionInfo,omitempty"`
	// Specifies which metrics are gathered for the MSK cluster. This property has
	// the following possible values: DEFAULT, PER_BROKER, PER_TOPIC_PER_BROKER,
	// and PER_TOPIC_PER_PARTITION. For a list of the metrics associated with each
	// of these levels of monitoring, see Monitoring (https://docs.aws.amazon.com/msk/latest/developerguide/monitoring.html).
	EnhancedMonitoring  *string      `json:"enhancedMonitoring,omitempty"`
	KafkaVersion        *string      `json:"kafkaVersion,omitempty"`
	LoggingInfo         *LoggingInfo `json:"loggingInfo,omitempty"`
	NumberOfBrokerNodes *int64       `json:"numberOfBrokerNodes,omitempty"`
	// JMX and Node monitoring for the MSK cluster.
	OpenMonitoring *OpenMonitoringInfo `json:"openMonitoring,omitempty"`
	// Controls storage mode for various supported storage tiers.
	StorageMode *string `json:"storageMode,omitempty"`
}

// Contains information about provisioned throughput for EBS storage volumes
// attached to kafka broker nodes.
type ProvisionedThroughput struct {
	Enabled          *bool  `json:"enabled,omitempty"`
	VolumeThroughput *int64 `json:"volumeThroughput,omitempty"`
}

// Public access control for brokers.
type PublicAccess struct {
	Type *string `json:"type,omitempty"`
}

// Specifies configuration for replication between a source and target Kafka
// cluster.
type ReplicationInfo struct {
	SourceKafkaClusterARN *string `json:"sourceKafkaClusterARN,omitempty"`
	TargetKafkaClusterARN *string `json:"targetKafkaClusterARN,omitempty"`
}

// Specifies configuration for replication between a source and target Kafka
// cluster (sourceKafkaClusterAlias -> targetKafkaClusterAlias)
type ReplicationInfoDescription struct {
	SourceKafkaClusterAlias *string `json:"sourceKafkaClusterAlias,omitempty"`
	TargetKafkaClusterAlias *string `json:"targetKafkaClusterAlias,omitempty"`
}

// Summarized information of replication between clusters.
type ReplicationInfoSummary struct {
	SourceKafkaClusterAlias *string `json:"sourceKafkaClusterAlias,omitempty"`
	TargetKafkaClusterAlias *string `json:"targetKafkaClusterAlias,omitempty"`
}

// Details about the state of a replicator
type ReplicationStateInfo struct {
	Code    *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

// Information about a replicator.
type ReplicatorSummary struct {
	CreationTime          *metav1.Time `json:"creationTime,omitempty"`
	CurrentVersion        *string      `json:"currentVersion,omitempty"`
	IsReplicatorReference *bool        `json:"isReplicatorReference,omitempty"`
	ReplicatorARN         *string      `json:"replicatorARN,omitempty"`
	ReplicatorName        *string      `json:"replicatorName,omitempty"`
	ReplicatorResourceARN *string      `json:"replicatorResourceARN,omitempty"`
}

type S3 struct {
	Bucket  *string `json:"bucket,omitempty"`
	Enabled *bool   `json:"enabled,omitempty"`
	Prefix  *string `json:"prefix,omitempty"`
}

// Details for client authentication using SASL.
type SASL struct {
	// Details for IAM access control.
	IAM *IAM `json:"iam,omitempty"`
	// Details for SASL/SCRAM client authentication.
	SCRAM *SCRAM `json:"scram,omitempty"`
}

// Details for SASL/SCRAM client authentication.
type SCRAM struct {
	Enabled *bool `json:"enabled,omitempty"`
}

// Details for client authentication using SASL.
type ServerlessSASL struct {
	// Details for IAM access control.
	IAM *IAM `json:"iam,omitempty"`
}

type StateInfo struct {
	Code    *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

// Contains information about storage volumes attached to MSK broker nodes.
type StorageInfo struct {
	// Contains information about the EBS storage volumes attached to Apache Kafka
	// broker nodes.
	EBSStorageInfo *EBSStorageInfo `json:"ebsStorageInfo,omitempty"`
}

// Details for client authentication using TLS.
type TLS struct {
	CertificateAuthorityARNList []*string `json:"certificateAuthorityARNList,omitempty"`
	Enabled                     *bool     `json:"enabled,omitempty"`
}

// Details about topic replication.
type TopicReplication struct {
	CopyAccessControlListsForTopics *bool `json:"copyAccessControlListsForTopics,omitempty"`
	CopyTopicConfigurations         *bool `json:"copyTopicConfigurations,omitempty"`
	DetectAndCopyNewTopics          *bool `json:"detectAndCopyNewTopics,omitempty"`
}

// Details for updating the topic replication of a replicator.
type TopicReplicationUpdate struct {
	CopyAccessControlListsForTopics *bool `json:"copyAccessControlListsForTopics,omitempty"`
	CopyTopicConfigurations         *bool `json:"copyTopicConfigurations,omitempty"`
	DetectAndCopyNewTopics          *bool `json:"detectAndCopyNewTopics,omitempty"`
}

type Unauthenticated struct {
	Enabled *bool `json:"enabled,omitempty"`
}

// Error info for scram secret associate/disassociate failure.
type UnprocessedSCRAMSecret struct {
	ErrorCode    *string `json:"errorCode,omitempty"`
	ErrorMessage *string `json:"errorMessage,omitempty"`
	SecretARN    *string `json:"secretARN,omitempty"`
}

// Description of the requester that calls the API operation.
type UserIdentity struct {
	PrincipalID *string `json:"principalID,omitempty"`
}

// The configuration of the Amazon VPCs for the cluster.
type VPCConfig struct {
	SecurityGroupIDs []*string `json:"securityGroupIDs,omitempty"`
	SubnetIDs        []*string `json:"subnetIDs,omitempty"`
}

// The VPC connection object.
type VPCConnection struct {
	Authentication   *string      `json:"authentication,omitempty"`
	CreationTime     *metav1.Time `json:"creationTime,omitempty"`
	TargetClusterARN *string      `json:"targetClusterARN,omitempty"`
	VPCConnectionARN *string      `json:"vpcConnectionARN,omitempty"`
	VPCID            *string      `json:"vpcID,omitempty"`
}

// Description of the VPC connection.
type VPCConnectionInfo struct {
	CreationTime     *metav1.Time `json:"creationTime,omitempty"`
	Owner            *string      `json:"owner,omitempty"`
	VPCConnectionARN *string      `json:"vpcConnectionARN,omitempty"`
}

// Description of the VPC connection.
type VPCConnectionInfoServerless struct {
	CreationTime     *metav1.Time `json:"creationTime,omitempty"`
	Owner            *string      `json:"owner,omitempty"`
	VPCConnectionARN *string      `json:"vpcConnectionARN,omitempty"`
}

// Details for IAM access control for VPC connectivity.
type VPCConnectivityIAM struct {
	Enabled *bool `json:"enabled,omitempty"`
}

// Details for SASL/SCRAM client authentication for VPC connectivity.
type VPCConnectivitySCRAM struct {
	Enabled *bool `json:"enabled,omitempty"`
}

// Details for TLS client authentication for VPC connectivity.
type VPCConnectivityTLS struct {
	Enabled *bool `json:"enabled,omitempty"`
}

// Zookeeper node information.
type ZookeeperNodeInfo struct {
	AttachedENIID      *string   `json:"attachedENIID,omitempty"`
	ClientVPCIPAddress *string   `json:"clientVPCIPAddress,omitempty"`
	Endpoints          []*string `json:"endpoints,omitempty"`
	ZookeeperVersion   *string   `json:"zookeeperVersion,omitempty"`
}
