// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// VpcConnectionSpec defines the desired state of VpcConnection.
//
// The VPC connection object.
type VPCConnectionSpec struct {

	// The authentication type of VPC connection.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	// +kubebuilder:validation:Required
	Authentication   *string                                    `json:"authentication"`
	ClientSubnetRefs []*ackv1alpha1.AWSResourceReferenceWrapper `json:"clientSubnetRefs,omitempty"`
	// The list of client subnets.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	ClientSubnets     []*string                                  `json:"clientSubnets,omitempty"`
	SecurityGroupRefs []*ackv1alpha1.AWSResourceReferenceWrapper `json:"securityGroupRefs,omitempty"`
	// The list of security groups.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	SecurityGroups []*string `json:"securityGroups,omitempty"`
	// A map of tags for the VPC connection.
	Tags map[string]*string `json:"tags,omitempty"`
	// The cluster Amazon Resource Name (ARN) for the VPC connection.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	TargetClusterARN *string                                  `json:"targetClusterARN,omitempty"`
	TargetClusterRef *ackv1alpha1.AWSResourceReferenceWrapper `json:"targetClusterRef,omitempty"`
	// The VPC ID of VPC connection.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	VPCID  *string                                  `json:"vpcID,omitempty"`
	VPCRef *ackv1alpha1.AWSResourceReferenceWrapper `json:"vpcRef,omitempty"`
}

// VPCConnectionStatus defines the observed state of VPCConnection
type VPCConnectionStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The creation time of VPC connection.
	// +kubebuilder:validation:Optional
	CreationTime *metav1.Time `json:"creationTime,omitempty"`
	// The State of Vpc Connection.
	// +kubebuilder:validation:Optional
	State *string `json:"state,omitempty"`
}

// VPCConnection is the Schema for the VPCConnections API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type VPCConnection struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              VPCConnectionSpec   `json:"spec,omitempty"`
	Status            VPCConnectionStatus `json:"status,omitempty"`
}

// VPCConnectionList contains a list of VPCConnection
// +kubebuilder:object:root=true
type VPCConnectionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []VPCConnection `json:"items"`
}

func init() {
	SchemeBuilder.Register(&VPCConnection{}, &VPCConnectionList{})
}
